//! Device pairing management commands for Syscity
//!
//! Provides CLI access to device pairing state: list, approve, reject, revoke.
//! Calls the gateway over WebSocket (device.pairing.*). `qr` uses local
//! generation (the QR is a static payload, not a daemon call).

use clap::Subcommand;
use serde_json::json;

use crate::cli::ws;
use crate::error::Result;

#[derive(Debug, Subcommand)]
pub enum DeviceCommands {
    /// List all pending and paired devices
    List,
    /// Approve a pending device pairing request
    Approve {
        /// Pairing code (e.g., A3F7K2X9)
        code: String,
    },
    /// Reject a pending device pairing request
    Reject {
        /// Pairing code
        code: String,
    },
    /// Revoke a paired device
    Revoke {
        /// Device ID
        id: String,
    },
    /// Show QR code SVG for a pairing request
    Qr {
        /// Pairing code
        code: String,
        /// Output file path (default: print SVG path)
        #[arg(short, long)]
        output: Option<String>,
    },
}

/// Run device commands (over WebSocket).
pub async fn run_device_command(command: &DeviceCommands) -> Result<()> {
    match command {
        DeviceCommands::List => {
            // Authorized devices
            let payload = ws::call("device.pairing.authorized", json!({})).await?;
            if let Some(devices) = payload.get("devices").and_then(|d| d.as_array()) {
                if devices.is_empty() {
                    println!("No paired devices.");
                } else {
                    println!("Paired Devices:");
                    println!("{:<20} {:<20}", "Device ID", "Name");
                    println!("{}", "-".repeat(45));
                    for dev in devices {
                        let id = dev.get("device_id").and_then(|v| v.as_str()).unwrap_or("-");
                        let name = dev
                            .get("display_name")
                            .and_then(|v| v.as_str())
                            .unwrap_or("-");
                        println!("{:<20} {:<20}", id, name);
                    }
                }
            }

            // Pending requests
            if let Ok(payload) = ws::call("device.pairing.pending", json!({})).await {
                if let Some(pending) = payload.get("pending").and_then(|r| r.as_array()) {
                    if !pending.is_empty() {
                        println!("\nPending Pairing Requests:");
                        println!("{:<12} {:<20}", "Code", "Device ID");
                        println!("{}", "-".repeat(35));
                        for req in pending {
                            let code = req.get("code").and_then(|c| c.as_str()).unwrap_or("-");
                            let dev_id =
                                req.get("device_id").and_then(|c| c.as_str()).unwrap_or("-");
                            println!("{:<12} {:<20}", code, dev_id);
                        }
                    }
                }
            }
        }
        DeviceCommands::Approve { code } => {
            match ws::call("device.pairing.approve", json!({ "code": code })).await {
                Ok(_) => println!("Approved pairing request {}", code),
                Err(e) => {
                    eprintln!("Failed to approve: {}", e);
                    return Err(e);
                }
            }
        }
        DeviceCommands::Reject { code } => {
            match ws::call("device.pairing.reject", json!({ "code": code })).await {
                Ok(_) => println!("Rejected pairing request {}", code),
                Err(e) => {
                    eprintln!("Failed to reject: {}", e);
                    return Err(e);
                }
            }
        }
        DeviceCommands::Revoke { id } => {
            match ws::call("device.pairing.revoke", json!({ "device_id": id })).await {
                Ok(_) => println!("Revoked device {}", id),
                Err(e) => {
                    eprintln!("Failed to revoke: {}", e);
                    return Err(e);
                }
            }
        }
        DeviceCommands::Qr { code, output } => {
            // The QR SVG is generated by the gateway (it knows the pairing payload
            // and brand); fetch it over WS `device.pairing.qr`.
            match ws::call("device.pairing.qr", json!({ "code": code })).await {
                Ok(payload) => {
                    let svg = payload["svg"].as_str().unwrap_or_default();
                    if let Some(path) = output {
                        tokio::fs::write(path, svg).await.map_err(|e| {
                            crate::error::SyscityError::Internal(format!(
                                "Failed to write QR: {}",
                                e
                            ))
                        })?;
                        println!("QR written to {}", path);
                    } else {
                        let tmp = std::env::temp_dir().join("syscity-pairing-qr.svg");
                        tokio::fs::write(&tmp, svg).await.map_err(|e| {
                            crate::error::SyscityError::Internal(format!(
                                "Failed to write QR: {}",
                                e
                            ))
                        })?;
                        println!("QR saved to {:?}", tmp);
                    }
                }
                Err(e) => {
                    eprintln!("Failed to reach daemon: {}", e);
                    return Err(e);
                }
            }
        }
    }
    Ok(())
}
