//! Setup wizard for Manta
//!
//! Interactive CLI wizard to generate initial `manta.yaml` configuration.

use crate::error::Result;
use clap::Subcommand;
use std::io::{self, Write};

#[derive(Debug, Subcommand)]
pub enum SetupCommands {
    /// Run the interactive setup wizard
    Init,
}

/// Run setup commands
pub async fn run_setup_command(command: &SetupCommands) -> Result<()> {
    match command {
        SetupCommands::Init => run_interactive_setup().await,
    }
}

async fn run_interactive_setup() -> Result<()> {
    println!("🐙 Manta Setup Wizard");
    println!("=====================\n");

    let config_path = crate::dirs::manta_dir().join("manta.yaml");

    if config_path.exists() {
        print!("Configuration already exists at {:?}. Overwrite? [y/N]: ", config_path);
        io::stdout().flush().unwrap();
        let mut input = String::new();
        io::stdin().read_line(&mut input).unwrap();
        if !input.trim().eq_ignore_ascii_case("y") {
            println!("Setup cancelled.");
            return Ok(());
        }
    }

    // Auth mode
    println!("\n1. Authentication Mode");
    println!("   - none:    No authentication (development only)");
    println!("   - token:   Shared secret token");
    println!("   - device:  Device pairing required");
    print!("   Select mode [token]: ");
    io::stdout().flush().unwrap();
    let mut auth_mode = String::new();
    io::stdin().read_line(&mut auth_mode).unwrap();
    let auth_mode = auth_mode.trim();
    let auth_mode = if auth_mode.is_empty() {
        "token"
    } else {
        auth_mode
    };

    // Shared token
    let shared_token = if auth_mode == "token" || auth_mode == "device" {
        print!("\n2. Shared Token (leave empty to auto-generate): ");
        io::stdout().flush().unwrap();
        let mut token = String::new();
        io::stdin().read_line(&mut token).unwrap();
        let token = token.trim();
        if token.is_empty() {
            let generated = format!("mt_{}", uuid::Uuid::new_v4().simple());
            println!("   Generated token: {}", generated);
            generated
        } else {
            token.to_string()
        }
    } else {
        String::new()
    };

    // Admin password
    print!("\n3. Admin Password (leave empty for none): ");
    io::stdout().flush().unwrap();
    let mut password = String::new();
    io::stdin().read_line(&mut password).unwrap();
    let password = password.trim().to_string();

    // Default model
    println!("\n4. Default Model Provider");
    println!("   - openai");
    println!("   - anthropic");
    println!("   - deepseek");
    println!("   - openrouter");
    print!("   Select provider [openai]: ");
    io::stdout().flush().unwrap();
    let mut provider = String::new();
    io::stdin().read_line(&mut provider).unwrap();
    let provider = provider.trim();
    let provider = if provider.is_empty() {
        "openai"
    } else {
        provider
    };

    // API key
    print!("\n5. API Key for {}: ", provider);
    io::stdout().flush().unwrap();
    let mut api_key = String::new();
    io::stdin().read_line(&mut api_key).unwrap();
    let api_key = api_key.trim().to_string();

    // Channels
    println!("\n6. Channels to enable (comma-separated, e.g., telegram,discord,slack)");
    print!("   Channels []: ");
    io::stdout().flush().unwrap();
    let mut channels = String::new();
    io::stdin().read_line(&mut channels).unwrap();
    let channels: Vec<String> = channels
        .trim()
        .split(',')
        .filter(|s| !s.is_empty())
        .map(|s| s.trim().to_string())
        .collect();

    // Build config YAML
    let mut config_lines = vec![
        "# Manta Configuration".to_string(),
        "# Generated by manta setup".to_string(),
        "".to_string(),
        "[gateway]".to_string(),
        "host = \"0.0.0.0\"".to_string(),
        "port = 18080".to_string(),
        "".to_string(),
        "[security]".to_string(),
        format!("auth_mode = \"{}\"", auth_mode),
    ];

    if !shared_token.is_empty() {
        config_lines.push(format!("shared_token = \"{}\"", shared_token));
    }
    if !password.is_empty() {
        config_lines.push(format!("admin_password = \"{}\"", password));
    }

    config_lines.push("".to_string());
    config_lines.push("[model]".to_string());
    config_lines.push(format!("default_provider = \"{}\"", provider));
    if !api_key.is_empty() {
        config_lines.push(format!("api_key = \"{}\"", api_key));
    }

    if !channels.is_empty() {
        config_lines.push("".to_string());
        config_lines.push("[[channels]]".to_string());
        for (i, ch) in channels.iter().enumerate() {
            if i > 0 {
                config_lines.push("[[channels]]".to_string());
            }
            config_lines.push(format!("type = \"{}\"", ch));
            config_lines.push("enabled = true".to_string());
        }
    }

    let config_content = config_lines.join("\n");

    // Ensure directory exists
    if let Some(parent) = config_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    std::fs::write(&config_path, config_content)?;

    println!("\n✅ Configuration written to {:?}", config_path);
    println!("\nNext steps:");
    println!("  1. Review the configuration: manta config show");
    println!("  2. Start the daemon:        manta start");
    println!("  3. Check health:            manta health");

    Ok(())
}
