//! `SecretStore` unified abstraction layer.
//!
//! Defines the logical secret identifier, origin classification, backend trait
//! and storage tiers. The existing `SecretResolver` (env/file/exec reference
//! resolution) coexists with this layer: the resolver turns config "references"
//! into values, the store handles key/value persistence.

use std::fmt;

/// Logical secret identifier — a value is an entry in a Tier 1/2 backend; a
/// reference is a key in config.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct SecretId {
    /// Namespace: "llm" | "mcp" | "mcp-env" | "mcp-oauth" | "channel" |
    /// "webhook" | "security" | "plugin".
    pub namespace: String,
    /// Entity: provider / server_id / channel id / fixed name.
    pub entity: String,
    /// Kind: "api_key" | "refresh_token" | "access_token" | "secret".
    pub kind: String,
}

impl SecretId {
    /// Construct a new secret id.
    pub fn new(namespace: &str, entity: &str, kind: &str) -> Self {
        Self {
            namespace: namespace.to_string(),
            entity: entity.to_string(),
            kind: kind.to_string(),
        }
    }

    /// Shortcut — kind defaults to "secret".
    pub fn secret(namespace: &str, entity: &str) -> Self {
        Self::new(namespace, entity, "secret")
    }
}

impl fmt::Display for SecretId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}/{}/{}", self.namespace, self.entity, self.kind)
    }
}

/// Secret origin — influences backend routing (see `choose_store`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SecretOrigin {
    /// Entered by the user (UI / config) → high-value, persistent → keyring
    /// preferred.
    UserEntered,
    /// Generated by the system (e.g. plugin secret_key) → file is fine.
    SystemGenerated,
    /// Injected by ops/environment (env / file / exec) → never persisted.
    OperatorInjected,
}

/// Storage tiers (maps to Tier 1-3 in the design doc).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SecretStoreTier {
    /// OS keyring (default; macOS Keychain / Windows DPAPI / Linux Secret
    /// Service).
    Keyring,
    /// 0600 file fallback (`~/.syscity/secrets/{namespace}/{entity}.toml`).
    File,
    /// Memory only (zeroize).
    Memory,
}

/// Unified backend storage trait.
///
/// Uses `async_trait` so it is dyn-compatible (`Arc<dyn SecretStore>` for
/// backend routing).
#[async_trait::async_trait]
pub trait SecretStore: Send + Sync {
    /// Read a secret; returns `Ok(None)` when absent or unreadable.
    async fn get(&self, id: &SecretId) -> crate::Result<Option<String>>;

    /// Write (overwrite) a secret.
    async fn set(&self, id: &SecretId, value: &str, origin: SecretOrigin) -> crate::Result<()>;

    /// Delete a secret (missing is not an error).
    async fn delete(&self, id: &SecretId) -> crate::Result<()>;

    /// Whether a secret exists.
    async fn has(&self, id: &SecretId) -> bool;
}

/// Redacted Debug: the `SecretId` is shown, values are never visible.
impl fmt::Debug for dyn SecretStore {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("SecretStore { .. }")
    }
}

/// Backend routing — picks a backend based on the secret id.
///
/// Phase 0 (no keyring): always file-backed. Phase 1 will prefer keyring based
/// on the `BACKEND` probe result; memory-only classes (e.g. `access_token`)
/// will route to a shared `MemoryStore`.
pub fn choose_store(id: &SecretId) -> std::sync::Arc<dyn SecretStore> {
    std::sync::Arc::new(crate::secrets::file_store::FileStore::new(&id.namespace))
}
